version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli
      - aws --version
  pre_build:
    commands:
      - echo "Decrypting Docker password..."
      - DOCKER_PASSWORD=Vivek#@121#
      - echo "Logging in to Docker Hub..."
      - docker login -u viveksaini2612 -p $DOCKER_PASSWORD
      - echo "Building Docker image..."
      - docker build -t viveksaini2612/lwweb .
  build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push viveksaini2612/lwweb
  post_build:
    commands:
      - echo "Cleaning up..."
      - docker logout

artifacts:
  files:
    - '**/*'